### ISSUE TITLE
Upgrade to Syn 0.12

### ISSUE THREAD

**Issue by fafhrd91** [PyO3/pyo3#103]

**Comment by fafhrd91** [comment]
now we can have access to span info, we need to explore better error reporting during macro expansion

**Comment by althonos** [comment]
I've started work on `syn 0.13` in the `syn13` branch.

**Comment by konstin** [comment]
@althonos I'm going to merge #154 than as we otherwise get horrible merge conflicts

**Comment by althonos** [comment]
@konstin yes that would be great ! I started toying around without really thinking I'd be able to do the port, but it's not as difficult as I thought it would be.

**Comment by althonos** [comment]
Ok so here's the progress so far: porting is not so complicated, as most of the changes reduce to types being renamed and `syn` dropping enum types everywhere (this makes the code a lot less verbose in the `match` blocks).

But what bugs me is the parsing / serializing part, as the current workflow is that the macros are filled with fudges that were necessary with `syn 0.11` but are not anymore. The main quirk is that the whole crate was mostly built to parse `String` instead of `TokenStream`, which makes it hard to use the new `Span` feature along other things. 

I think I'll work on a fresh implementation of the crate, but this'll take a lot more time.

**Comment by konstin** [comment]
>  The main quirk is that the whole crate was mostly built to parse String instead of TokenStream, which makes it hard to use the new Span feature along other things.

For all I know it's just replacing

```rust
let source = input.to_string();
let mut ast = syn::parse_item(&source).unwrap();
```

with 

```rust
let mut ast: syn::ItemStruct = syn::parse(input).unwrap();
```

six times in pyo3cls/lib.rs and activating the nightly feature on proc-macro2.

**Comment by althonos** [comment]
Not only, because for instance the `#[pyclass]` arguments are passed as `String` everywhere, and then parsed internally using `syn::TokenTree` which was dropped in v0.13.

**Comment by konstin** [comment]
TokenTree just moved into [proc_macro2](https://docs.rs/proc-macro2/0.3.8/proc_macro2/enum.TokenTree.html), so for now we can use proc_macro2::TokenTree.

**Comment by althonos** [comment]
@konstin : I ended up parsing the `#[class(...)]` arguments using a `Punctuated<Expr, Comma>`, it works better than the current homemade parser in `py_class.rs`.
