### ISSUE TITLE
Rename master branch to main or so

### ISSUE THREAD

**Issue by kngwyu** [PyO3/pyo3#1130]
It can cause inconvenience for a while but will be beneficial for this project.
Github provides some references for this:
https://github.com/github/renaming
https://github.blog/changelog/2020-08-26-set-the-default-branch-for-newly-created-repositories/

Though I have to practice renaming in some personal projects.

**Comment by davidhewitt** [comment]
What's your intended benefit of doing this?

**Comment by davidhewitt** [comment]
Ah, I'd missed this discussion earlier in the year but agree with it's points and happy to support the movement: https://dev.to/rhymu8354/git-renaming-the-master-branch-137b

**Comment by davidhewitt** [comment]
`main` sounds like the new standard people are converging on, so that gets my vote

**Comment by davidhewitt** [comment]
FWIW I suggest we do this move later in the year when Github releases "seamless move" for the default branch: https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

**Comment by roblabla** [comment]
Another reason to wait for seamless move: for git dependencies, `cargo` defaults the `branch` argument to master. Once renamed, the user will get the frustrating message "failed to find branch `master`". I *think* if github automatically redirects git fetch, it should fix the problem.

**Comment by davidhewitt** [comment]
Github now supports the seamless move: https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/

I'll make the renaming at the weekend unless I hear a reason not to! @kngwyu

**Comment by roblabla** [comment]
May I request either waiting for https://github.com/rust-lang/cargo/pull/9133 to be into stable (which should happen in 1.52, I believe), or alternatively keeping the old master branch around for compatibility with people using pyo3 through git dependencies?

The current behavior of cargo with git dependencies is to assume the default branch is `master` (instead of using whatever is the default, e.g. HEAD). If the branch is renamed without keeping the old branch, it will break existing git dependencies. Even with github's seamless move, I believe it won't actually be seamless because of cargo's issues.

**Comment by davidhewitt** [comment]
So I just tested it the rename with [`pythonize`](https://github.com/davidhewitt/pythonize). Because Github redirects https requests from `master` to `main` as part of the seamless rename, this worked seamlessly without breakage:

```
pythonize = { git = "https://github.com/davidhewitt/pythonize" }
```

However if I change to use the ssh protocol, e.g.

```
pythonize = { git = "ssh://git@github.com/davidhewitt/pythonize" }
```

then indeed `cargo build` fails because it's still looking for `master`:

```
 fatal: couldn't find remote ref refs/heads/master
``` 

My personal opinion is that because the https URL will continue to work fine, it's ok for us to proceed. But I will wait for confirmation from someone else, as users on Rust older than 1.52 will not be able to use git ssh dependencies. I doubt many (any?) users are doing this.

**Comment by roblabla** [comment]
Ah, alright, that sounds fine then. I was under the impression that https clone would have the same problem, but if they work, then there should be no problem! Thanks for checking :).
