### ISSUE TITLE
PyPy Support via cpyext - What's needed?

### ISSUE THREAD

**Issue by omerbenamram** [PyO3/pyo3#129]
Hi, 
I've been messing around with pyo3 and have been really enjoying it - the simplicity is fantastic, and it seems overhead with cpython is minimal, and very pleasant to work with.
Our production parsing systems run PyPy for the massive speedup gains we get for some text parsing cases we have implemented in python.
From my benchmarks, implementing identical parsers in rust yield around 250x~ time the speed of cpython, and around 15x that of pypy.

However for gradual migration we'd probably want to be able to load the rust extensions side-by-side with out running pypy processes.

It does seem that PyO3 recognizes pypy to some degree, as I did get two seperate shared libs
![image](https://user-images.githubusercontent.com/2467993/36799382-bdb1b240-1cb5-11e8-9058-f80d32fe115c.png)

 I've tried fiddling a little bit with PyO3 building code (on mac), but wasn't able to make anything meaningful so far 😕 
![image](https://user-images.githubusercontent.com/2467993/36799205-4881fb06-1cb5-11e8-9845-5851057781aa.png)

Do you think it would be a big undertaking to make PyO3 compatible with cpyext? if so, what would be needed to make this work?

Thanks alot!

**Comment by fafhrd91** [comment]
When I actively worked on pyo3 I looked to a cpyext compatibility. But decided against it because cpyext integration is super slow. Cffi integration with pypy is much faster. Personally I don’t have time to do any integration work. But I’ll accept PRs for sure.

To integrate with pypy you need 2 changes:

1. Add pypy detection to build.rs (easy)
2. Modify pyo3::ffi3 and limit exportable api

**Comment by fafhrd91** [comment]
please reopen, if you have more questions
