### ISSUE TITLE
Returning a reference to an object to python

### ISSUE THREAD

**Issue by pizzooid** [PyO3/pyo3#1302]
Hi, I am sorry for asking a question regarding pyo3 I did not know where to ask and do not understand the documentation in this regard.

I am calling a rust library from python. I want to return a reference to a Rust object containing a large amount of data to be later called with some additional Data from python.

Can I do this without exposing the struct to python or at least without copying the data to python?

Or do you suggest a different approach?

Thank you for your help.
Best regards
P

**Comment by birkenfeld** [comment]
Welcome to PyO3! In general, the best place to ask such questions is the Gitter room, https://gitter.im/PyO3/Lobby

To address your problem specifically, it is not possible to return references (`&T`) or anything with a non-static lifetime to Python, since once on the Python side, you cannot restrict an object's lifetime anymore.  It is, however, possible to pass structs without them being exposed to Python. You only need a toplevel type that is `pyclass`, but it can have arbitrary members that are not accessible from the Python side directly.

Instead of references, you should normally use reference-counted pointers, i.e. `Arc<T>` (or `Arc<Mutex<T>>`) if private to Rust code or `Py<T>` if exposed as a Python object.

Another simple way is to only give out "handles" (e.g. in the form of indices) to Python, and keep the data entirely on the Rust side.

If you have more info, we can help more accurately, but as I said please use the Gitter room for that.

**Comment by pizzooid** [comment]
Thank you
