### ISSUE TITLE
How to expose enums and constants to python module?

### ISSUE THREAD

**Issue by fcangialosi** [PyO3/pyo3#131]
If I'm using pyo3 to create a module called `Test` and I have some rust code like this

```rust
pub enum Event{
    A(u32),
    B(u32),
    ...
}

const X: u32 = 0;
```
How can I expose these to Python, e.g. as `Test.Event.A` and `Test.X`?

**Comment by fafhrd91** [comment]
i dont know :)

maybe class properties? you can create class and expose some properties or static methods

**Comment by fafhrd91** [comment]
technically, i think it is possible to bridge rust enums to a python enums, at least some subset, but that will require time

**Comment by snowmantw** [comment]
Hi @fafhrd91, because of my project needs to export Rust enum to Python enum, I'm wondering if it makes sense that turn Rust enum to PyTuple that already implemented in PyO3, that according to Python document [says](https://docs.python.org/3/library/enum.html#functional-api) the semantics of Python enum API resemble namedtuple?

**Comment by snowmantw** [comment]
Or I just make it as class...which seems also work as you commented.

**Comment by fafhrd91** [comment]
@snowmantw I don’t maintain this library anymore. @konstin is maintainer

**Comment by ckaran** [comment]
@konstin Can you create a small, complete example of how to make bindings that pass python enum.Enum to rust and back again?  I keep getting errors each time I try to do it, and I'm the point where I'm passing `u8` back and forth just because it's easier, but it really breaks the mental model to do so.

**Comment by sweihub** [comment]
Copy from the PyO3 docs

```rust
use pyo3::prelude::*;

#[pymodule]
fn my_module(py: Python<'_>, module: &PyModule) -> PyResult<()> {
     let submodule = PyModule::new(py, "submodule")?;
     submodule.add("super_useful_constant", "important")?;

     module.add_submodule(submodule)?;
     Ok(())
}
 ```
