### ISSUE TITLE
Use shifting and masking to convert between 128-bit Rust integers and Python integers

### ISSUE THREAD

**Issue by programmerjake** [PyO3/pyo3#1314]
@kngwyu in https://github.com/PyO3/pyo3/issues/1310#issuecomment-743722886_
> >  to use PyNumber_ APIs to shift and mask the number to get two values that fit into u64's.
> 
> I tried that first but I found it too complex, especially for `i128`, though it is faster...

We should use the faster method anyway, I don't think it'll be that much more complex.

**Comment by kngwyu** [comment]
So... yeah, I think it's good if we can smartly implement it, but what is worse than code complexity, I noticed that we cannot access `lshift` and `add` with LIMITED_API.
Specifically, calling `ffi::PyType_GetSlot(&mut ffi::PyLong_Type, ffi::Py_nb_add)` fails with `SystemError`, since CPython does not allow getting slot methods of non-heap types... (`PyLong_Type` is statically allocated and not a heap type).

**Comment by birkenfeld** [comment]
`PyNumber_And` and `PyNumber_Rshift` are the only thing necessary, at least for u128, no?

**Comment by kngwyu** [comment]
Ah, thanks, I forgot these abstract methods.
