### ISSUE TITLE
Unsafe usages in PyByteArray

### ISSUE THREAD

**Issue by nw0** [PyO3/pyo3#1392]
I was looking at unsafe functions and `PyByteArray`'s `data`, `as_bytes`, `as_bytes_mut` (since #967) and `resize` seem unusually unsafe. We have:

```rust
impl PyByteArray{
    // Given a shared reference, return a mutable (!) raw pointer to the underlying data (so says the CPython source)
    pub fn data(&self) -> *mut u8 { ... }
    // Given a shared reference, return a slice of the underlying data
    pub unsafe fn as_bytes(&self) -> &[u8] { ... }
    // Given a shared reference, return a mutable (!) slice of the underlying data
    pub unsafe fn as_bytes_mut(&self) -> &mut [u8] { ... }
    // Given a shared reference, possibly move the underlying data
    pub fn resize(&self, len: usize) -> PyResult<()> { ... }
}
```

Compare this to `Vec` (methods with corresponding return types):
```rust
impl<T> Vec<T> {
    pub fn as_mut_ptr(&mut self) -> *mut T { ... }
    pub fn as_slice(&self) -> &[T] { ... }
    pub fn as_mut_slice(&mut self) -> &mut [T] { ... }
    pub fn resize(&mut self, new_len: usize, value: T) { ... }
}
```

It feels like `data`, `as_bytes_mut`, `resize` should require `&mut self` (as in `Vec`), to prevent Rust code from triggering the underlying buffer to move while in use. Additionally, I'm of the opinion that `data` (as implemented) should `unsafe`, as the return type has no lifetime bound, and the underlying data could be moved away, resulting in a use-after-free.

As implemented, it appears to be sound (since we can't deref the `*mut u8` without unsafe code). However, the papercut factor is definitely present.

From the comments, another reasonable possibility could be to require the GIL in order to bound the lifetimes of the returned values. Then these (or similar operations with different names) could be made safe (?). I'm not sure if this is a palatable solution to consumers, although from the scenario in #632, this isn't an issue.

**Comment by birkenfeld** [comment]
The pertinent comparison here is not to `Vec`, but to `PyList`: it's fine for all methods to take `&self`.  You should never be able to get a hold of a `&PyByteArray` that isn't bound by a GIL lifetime, so this acts as the needed synchronization.

**Comment by programmerjake** [comment]
I think part of why the methods returning slices are unsafe is that you could call `allow_threads` and unlock the GIL but still be able to use a byte slice since `&[u8]` is `Sync + Send`. This can lead to a data race or a use after free.

Also, the method returning `&mut [u8]` is unsafe since you could call it multiple times getting overlapping mutable references which is undefined behavior.

If those methods were changed to return `&[Cell<u8>]` that would be safer since `Cell` is not `Sync` and since it's not a mutable reference.

**Comment by birkenfeld** [comment]
The documentation already has a big "Safety" heading for both `as_slice` and `as_mut_slice` explaining the unsafety.

As for `data`, it appears to be a convention that `as_ptr` like methods that return raw pointers are not unsafe to call.

**Comment by davidhewitt** [comment]
Thanks for the discussion. Here's my reasoning behind the current design and why I think it's correct. Always open to further feedback!

First, regarding `&mut self` - all PyO3 native types are always `&` rather than `&mut` references. To try to explain this point - they all are like `Arc` under the hood thanks to Python reference counting. Consider for example this code:

```rust
let byte_array = PyByteArray::new(py, b"foo");
let obj = byte_array.to_object(py);  // makes a new PyObject which refers to the same byte_array
// do something with byte_array 
py_run!(py, obj, "obj += obj[:]");  // append a copy of the byte array to itself; this has modified the contents and probably triggers a resize
```

In the snippet above, both `byte_array` and `obj` refer to the same object. `&mut self` is therefore out of our reach - we can't ever guarantee unique access to a Python object.

----

Now, for the APIs themselves:

`PyByteArray::data` is simply creating a pointer to the underlying storage. This is a completely safe operation - no matter how many times you call this function, if you do nothing with the result you're not going to run into undefined behaviour. Just like `Vec::as_mut_ptr`, it's how you consume the raw pointer which matters. If you get use-after-free because you used `unsafe` to dereference this pointer after it was invalidated, that error's on you, not `PyByteArray::data`.

`PyByteArray::resize` is similarly safe to call: just like `Vec::resize`, we're able to safely call this as many times as we like (in isolation) without running into issues. Yes, we take `&self` instead of `&mut self`, which looks a little weird, but as @birkenfeld points out, `&self` is already scoped to mean that we hold the GIL. That guarantees that no other thread is accessing the data at the same time. 

However, can the same thread that's calling `.resize()` be accessing the data? Yes, but only through three ways:
- by using `unsafe` to derefence the pointer that came from `PyByteArray::data`
- by using the `unsafe` method `as_bytes`
- by using the `unsafe` method `as_bytes_mut`

With both of the latter two methods, your responsibility of usage is already documented on them. From the snippet seen at the top of my post, it's evidenced `.resize()` isn't the only way to invalidate these slices. The `py_run!` call caused a resize implicitly. (Basically any Python code could eventually cause a resize and invalidate the pointers; it's all opaque to the Rust compiler.)
----

> If those methods were changed to return &[Cell<u8>] that would be safer since Cell is not Sync and since it's not a mutable reference.

I've considered this in the past. Because the resize can happen at any time outside of the Rust compiler's ability to verify, these slice-returning methods have to be `unsafe`. As that's the case, I think it's best to embrace the unsafety and make them slightly easier to work with; `&[Cell<u8>]` is really cumbersome to use imo. If you think there's value, we could add `.as_cell_slice()` - but because it'll still be `unsafe` I think that most people will just use `.as_bytes()`.

**Comment by nw0** [comment]
Thanks everyone for your replies! I'm grateful that you've taken the time to write it out so clearly. I'd been using PyO3 for some time, but never quite understood from the book what was going on with Python object references (and I've certainly got much more to learn here).

> I think part of why the methods returning slices are unsafe is that you could call `allow_threads` and unlock the GIL but still be able to use a byte slice since `&[u8]` is `Sync + Send`. This can lead to a data race or a use after free.

> ```
> py_run!(py, obj, "obj += obj[:]");  // append a copy of the byte array to itself; this has modified the contents and probably triggers a resize
> ```

These examples were especially helpful. I wonder if it'd be useful for some of this to be spelled out in https://pyo3.rs/v0.13.1/types.html#mutability-and-rust-types ?

**Comment by davidhewitt** [comment]
👍 opened another ticket to remind myself to do that sometime!
