### ISSUE TITLE
option to select the python installation used

### ISSUE THREAD

**Issue by jimy-byerley** [PyO3/pyo3#1396]
Hello dear developers,

I'm writing some rust program calling python modules. As scripting is part of my software functions, I wanted to allow the user to choose which installation of python is used (the system provided installation, or an other packed by the software). The issue is that rust links to the python shared library (and version therefore) which is managed by the OS

```bash
$ ldd my_executable
libpython3.8.so.1.0 => /lib/x86_64-linux-gnu/libpython3.8.so.1.0 (0x00007f69a9555000)
```

I know I can choose the LDPATH so that the OS will look at an other directory, but the version name is also an issue: I want the users to be able to choose their own python version.
Pyo3 is already tolerant to the python version we are using, so this is just a linker issue.

**Could it be possible to select the python installation from rust ? something like:**
```rust
pyo3::link_python(Path::new("/lib/x86_64-linux-gnu/libpython3.8.so.1.0"));
let gil = Python::acquire_gil();
let py = gil.python();
```

**Comment by davidhewitt** [comment]
Hi, thanks for the question.

I think due to the nature of linking, LDPATH is the only option you have. The symbols have to be resolved during program load time? By the time any Rust code starts executing, it's too late.

I suggest an alternative design: instead of packaging a Rust program calling Python modules, I suggest you package your program as an extension module and put a small script in Python as the entry point to call into it.

With the `abi3` feature and `maturin` it would be very easy for you to make a wheel which can be installed on multiple different Python versions as suits your users.

You could also look at projects like `PyOxidizer` which allow you to package your rust code an Python interpreter all in one.

**Comment by jimy-byerley** [comment]
Thanks for the answer and all the options :)
Well my case is a bit more tricky. I'm working on a proprietary software in which the python part must be hidden. To have a python script running it could be a weakness in my application ... I will figure it out.

**Comment by davidhewitt** [comment]
👍 just as a final thing, I wanted to add that of you want to allow different python versions you should use the `abi3` feature. It restricts pyO3 to only use python apis which do not change between interpreter versions.

Hope you manage to find a solution which is suitable for you!

**Comment by davidhewitt** [comment]
This question has been stale for many months, so I'm going to close it now.
