### ISSUE TITLE
PyO3 extension modules always link in miniz_oxide

### ISSUE THREAD

**Issue by ravenexp** [PyO3/pyo3#1407]
## 🐛 Bug Reports

When compiling the sample module rust2py from

https://pyo3.rs/v0.13.1/module.html#python-modules

cargo-bloat indicates that miniz_oxide symbols are linked in:

```
 File  .text     Size     Crate Name
 2.2%  13.7%  29.5KiB       std std::backtrace_rs::symbolize::gimli::elf::<impl std::backtrace_rs::symbolize::gimli::Mapping>::new
 1.1%   6.8%  14.7KiB       std addr2line::ResUnit<R>::parse_lines
 0.7%   4.4%   9.3KiB       std std::sys_common::backtrace::_print_fmt::{{closure}}
 0.6%   3.9%   8.3KiB       std miniz_oxide::inflate::core::decompress
```

I understand that 3.9% of `.text` is not much, but I wonder what is the zlib compression used for in this trivial module?

### 🌍 Environment

 - Your operating system and version: arch linux
 - Your python version: 3.9 (the module was compiled for abi3-py36)
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: no
 - Your Rust version (`rustc --version`): 1.49
 - Your PyO3 version: 0.13.1
 - Have you tried using latest PyO3 master (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: no

**Comment by davidhewitt** [comment]
Thanks for the question.

In the table you show, `cargo-bloat` shows the crate responsible is `std`. Indeed, this is what I see in the source for `std`: https://github.com/rust-lang/rust/blob/b5c496de374407c0937cf5257d89230b5358d053/library/std/Cargo.toml#L25-L28

So my assumption is that these are included via the rust standard library in order to have backtrace support.

Is this creating an issue?

**Comment by ravenexp** [comment]
Oh, you are right! I misinterpreted the cargo-bloat output.
pyo3 also has its own miniz_oxide crate dependency, which confused me.
This zlib inflate code seems to come from the std backtrace generator.

I'm closing this issue.
Thanks for the explanation!
