### ISSUE TITLE
Hygiene issues with `quote_spanned!`

### ISSUE THREAD

**Issue by scalexm** [PyO3/pyo3#1506]
Commit fe74160a from #1440 introduced the use of `quote_spanned!` in a few places. Hygiene rules specific to `quote_spanned!` make the following macro expansion to fail:
```rust
#[pyclass]
struct Foo {}

macro_rules! foo {
    (#[pymethods] $($body:tt)*) => {
        #[pymethods]
        $($body)*
    };
}

foo!(
    #[pymethods]
    impl Foo {
        fn foo(&self, py: Python<'_>) {}
    }
);
```

> error[E0425]: cannot find value `_py` in this scope

Was there a legitimate reason for these uses of `quote_spanned!`? Otherwise removing them altogether solves the problem.

**Comment by davidhewitt** [comment]
The motivation for `quote_spanned!` is that it gives much better error messages: code using `quote!` will mark the `#[pymethods]` attribute for errors such as conversion failures. With `quote_spanned!` we can mark the argument which is incorrect.

If we can fix this by tweaking the usage of `quote_spanned!` rather than removing them, that'd be preferable imo. I'll take a quick stab at that. Thanks for sharing the repro.
