### ISSUE TITLE
Module level '__doc__' attribute is automatically added to '__all__'

### ISSUE THREAD

**Issue by ravenexp** [PyO3/pyo3#1508]
### 🌍 Environment

 - Your operating system and version: Arch Linux-5.11.4 x86_64 with glibc-2.33
 - Your python version: 3.9.2
 - How did you install python (e.g. apt or pyenv)?: pacman Did you use a virtualenv?: yes
 - Your Rust version (`rustc --version`): 1.50.0
 - Your PyO3 version: 13.2
 - Have you tried using latest PyO3 main (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: no

### 💥 Reproducing

I created a new PyO3 project from [the module template](https://pyo3.rs/v0.13.2/module.html).

Running the following code in the Python REPL yields:

```
>>> import rust2py
>>> rust2py.__all__
['__doc__', 'sum_as_string']
```

I expect only `sum_as_string` to be included in `__all__`, mainly because
that's what users expect when they do `from rust2py import *`.

**Comment by mhils** [comment]
From a cursory glance, it seems like

https://github.com/PyO3/pyo3/blob/c0d49052b5f8d84a68b4d5d6c71c5def0bdc66a2/src/derive_utils.rs#L323

should be `setattr` instead of `add` and this should be fixed. 
Sorry for the drive-by comment, this just happend to show up in https://github.com/mitmproxy/pdoc/issues/235. 😇

**Comment by kngwyu** [comment]
Thank you both for reporting!
