### ISSUE TITLE
Question: Passing Python array (Vec<f64>) as a reference

### ISSUE THREAD

**Issue by rohitjoshi** [PyO3/pyo3#157]
I am returning `PyResult<Vec<f64>> ` from a rust function to python module.
How do I pass this object as a reference to next function?

e.g
 Below gives error because value passed by reference `&`
```
fn calc_y_py(_py: Python, dict: &PyDict, mu_z: &Vec<f64>, sigma_z_sqrt: &Vec<f64> ) -> PyResult<Vec<f64>> {
       let y = calc_y(&dict, mu_z.as_slice(), sigma_z_sqrt.as_slice());
       Ok(y)
    }
```
below works: where `mu_z` and `sigma_z_sqrt` are passed as object

```
fn calc_y_py(_py: Python, dict: &PyDict, mu_z: Vec<f64>, sigma_z_sqrt: Vec<f64> ) -> PyResult<Vec<f64>> {
       let y = calc_y(&dict, mu_z.as_slice(), sigma_z_sqrt.as_slice());
       Ok(y)
    }

```

**Comment by birkenfeld** [comment]
As far as I can see, there is no way to make this work since upon returning to Python, the `Vec<f64>` must be converted into a Python list of Python floats. Passing it back as a reference would require a Rust vector to be present somewhere in memory, which it isn't.

`&[f64]` would work if there was an array f64 in memory, but since they're Python floats on the Python side, they are boxed. You'd have to use `array.array` or [Numpy](https://github.com/rust-numpy/rust-numpy) to have a chance for zero-copy conversion.

**Comment by kngwyu** [comment]
I also recommend rust-numpy for this kind of usage.

**Comment by rohitjoshi** [comment]
Thanks
