### ISSUE TITLE
How to make Rust struct in other crate accessible from Python?

### ISSUE THREAD

**Issue by vedantroy** [PyO3/pyo3#1581]
I have a struct defined in a different crate that is a mildly complex Rust struct (I have simplified it here by replacing some types with `usize`):

```rust
#[derive(Debug, PartialEq, Clone)]
pub struct Backend {
    queue: Vec<usize>,
    states: HashMap<usize, usize>,
}
```

I am wondering how to expose this struct to Python. Currently, I do this:

```rust
#[pyclass(unsendable)]
struct PyBackend {
    backend: Backend,
}
```

but, the Python code cannot access the internal `backend` field.

I can solve this problem in a hacky way by using `#[getter]` plus `pythonize` to convert the `Backend` into a `dict`, but this does not feel very clean since:
1. A user must access everything by doing `foo.backend["queue|states"]` instead of just doing `foo.queue` or `foo.states`
2. It returns a dict instead of a Python class. 

Is there a way to make this feel more idiomatic?

Here's the full error:

```
error[E0277]: the trait bound `Backend: IntoPyCallbackOutput<_>` is not satisfied
   --> src/lib.rs:11:1
    |
11  | #[pyclass(unsendable)]
    | ^^^^^^^^^^^^^^^^^^^^^^ the trait `IntoPyCallbackOutput<_>` is not implemented for `Backend`
    | 
   ::: /home/vedantroy/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.13.2/src/callback.rs:170:8
    |
170 |     T: IntoPyCallbackOutput<U>,
    |        ----------------------- required by this bound in `pyo3::callback::convert`
    |
    = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Backend: PyClass` is not satisfied
  --> src/lib.rs:11:1
   |
11 | #[pyclass(unsendable)]
   | ^^^^^^^^^^^^^^^^^^^^^^ the trait `PyClass` is not implemented for `Backend`
   |
   = note: required because of the requirements on the impl of `pyo3::FromPyObject<'_>` for `Backend`
   = note: required by `extract`
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

And for what it's worth, the full struct is more complicated:

```rust
#[derive(Debug, PartialEq, Clone)]
pub struct Backend {
    queue: Vec<Change>,
    op_set: OpSet,
    states: HashMap<amp::ActorId, Vec<Change>>,
    actors: ActorMap,
    hashes: HashMap<amp::ChangeHash, Change>,
    history: Vec<amp::ChangeHash>,
}
```

**Comment by davidhewitt** [comment]
Because `Backend` is in a thirdparty crate and we can't use any pyo3 macros on it, any solution will require some manual boilerplate.

I'd recommend creating a `#[getter]` for each field you want to access, .e.g.

```
#[pymethods]
impl Foo {
    #[getter] 
    fn queue(self) -> Vec<usize> {
        self.backend.queue.clone()
    }
}
```

Now, you've got a lot of complex collection types in this `Backend` struct, like `Vec`, where at the moment it's necessary to clone them. As a result changes made in Python to that cloned list won't propagate back to Rust. If it's important for you for the collections to be modifiable from Python, you might want to write a more complex `PyFoo` class which contains items such as `queue: Py<PyList>`, and a conversion from `PyFoo` to `Foo`.

**Comment by vedantroy** [comment]
Thanks for the fast response!

Would you mind giving a quick outline of how a `PyFoo` class / conversion would look? Just need a bit of a foothold to get started.

**Comment by davidhewitt** [comment]
Something like this, perhaps:

```
#[pyclass(name = "Foo")]
class PyFoo {
    queue: Py<PyList>
}

struct Foo {
    queue: Vec<Change>
}

fn py_change_into_change(py_change: &PyAny) -> PyResult<Change> {
    todo!()
}

impl TryFrom<PyRef<'_, PyFoo>> for Foo {
    type Error = PyErr;
    fn try_from(py_foo: PyRef<'_, PyFoo>) -> PyResult<Self> {
        let queue = py_foo.queue.iter().map(py_change_into_change).collect::<PyResult<_>>()?;
        Ok(Foo {
            queue
        })
    } 
}
```

**Comment by vedantroy** [comment]
Thanks for taking the time to write out an example!

A few questions that may also be useful for a future passersby:
- What does `type Error = PyErr;` do?
- It looks like this handles conversion from Python objects to Rust objects but not the other way around. What is the scenario where this matters? (I.e, I see the value in the `#[getter]` methods because they allow Python to access Rust struct fields, but not sure I see the purpose here).
- Speaking of Python to Rust conversions and not vice-versa, does this snippet help solve the problem of "I have a Rust method that returns `Foo` and I want to return a `PyFoo` to the user"?
- I'm guessing `Foo` corresponds to `Backend` in the original example, but, `Foo` would have to be in the same crate to implement the `TryFrom<...>` trait. Is the solution just to duplicate the `Backend` struct into the same crate, and if a method returns a `Backend` struct from the other crate, manually transfer the fields?

**Comment by mejrs** [comment]
> What does type Error = PyErr; do?

This is just std's `TryFrom` trait, which requires writing this down.

> does this snippet help solve the problem of "I have a Rust method that returns Foo and I want to return a PyFoo to the user"?

If you own `Foo`, you can just make `Foo` a pyclass to begin with - they're still usable as usual by other Rust code. Otherwise I'd just wrap it (and delegate everything to the inner `Foo`).

```
#[pyclass(name = "Foo")] 
struct PyFoo{
    inner: Foo
}
```
> I'm guessing Foo corresponds to Backend in the original example, but, Foo would have to be in the same crate to implement the TryFrom<...> trait. Is the solution just to duplicate the Backend struct into the same crate, and if a method returns a Backend struct from the other crate, manually transfer the fields?

I'm not 100% sure what you are asking, but if you want to deal with the orphan rule (you can't implement a trait on a type if neither belongs to you), the typical way to deal with it is to wrap it in a newtype like I did above.

**Comment by ChristopherRabotin** [comment]
Sorry to bump this up, but I was wondering whether that was still the best approach.

My case is very similar: I have a pretty large crate I use primarly in Rust, but would like to add the option of using in Python. All of my structs are defined in the Rust crate. I'm currently planning on creating a new crate for Python only. **Is this the recommended approach?**

Moreover, if I want to expose [`Orbit`](https://nyx-space.gitlab.io/nyx/src/nyx_space/cosmic/orbit.rs.html#98-117) to Python, is there a way to do something like this:

```
use nyx::cosmic::Orbit;
use pyo3::some_magic_wrapper;

some_magic_wrapper!(Orbit);
```

Or do I need to do the following:
```
use nyx::cosmic::Orbit as NOrbit;
use pyo3::prelude::*;

#[pyclass]
struct Orbit(NOrbit);

// Re-impl the many functions of Orbit with a `PyResult` return
```

Thanks

**Comment by davidhewitt** [comment]
`some_magic_wrapper!` is sadly not techinally feasible work because all Rust macros are dependent on the original source being delievered as input.

If Rust had compile-time reflection in the future, perhaps such a thing would be possible. But that's a _long_ way off; I haven't heard it discussed much ever. So the above recommendations still apply!

**Comment by mejrs** [comment]
@ChristopherRabotin You can do it in the same crate, if you want - Rust structs in the original crate can also be pyclasses and they can still be used by Rust code as before. 

There are some advantages and disadvantages to both:
- You can access private fields and methods in your Python implementation - you can't from another crate.
- If this is all in one crate you'll have to do some tricks with conditional compilation to not break every user without python installed.
- You'll have to write wrappers for structs with type/lifetime parameters either way.
- You'll have to write wrappers for your iterators because these don't play well with Python.
- You'll have to write a lot of boilerplate either way.
- Putting it all in new crate will avoid bloating the original crate.

With that said I would still recommend making a separate crate per the above advice.

**Comment by davidhewitt** [comment]
As this question has been solved, I'm going to close this issue. If anyone reading this has similar questions in future, please feel free to open a new issue.
