### ISSUE TITLE
Python 3.x interpreter not found

### ISSUE THREAD

**Issue by Johnz86** [PyO3/pyo3#1616]
### 🌍 Environment

 - Your operating system and version: Microsoft Windows 10 Enterprise, 10.0.18363 Build 18363
 - Your python version: Python 3.8.5
 - How did you install python (e.g. apt or pyenv)? Did you use a virtualenv?: no
 - Your Rust version (`rustc --version`): rustc 1.52.1 (9bc8c42bb 2021-05-09)
 - Your PyO3 version: 0.13.2
 - Have you tried using latest PyO3 main (replace `version = "0.x.y"` with `git = "https://github.com/PyO3/pyo3")?`: yes

### 💥 Reproducing
Check the python version available with commands
```
PS C:\GIT\Rust\call-python> py --version
Python 3.8.5
```
I set the python3 command alias in powershell with:
```
Set-Alias python3 py
Set-Alias python py
```
And check the python3 interpreter availability
```
PS C:\GIT\Rust\call-python> python --version
Python 3.8.5
PS C:\GIT\Rust\call-python> python3 --version
Python 3.8.5
```
cargo.toml
```toml
[package]
name = "call-python"
version = "0.3.0"
authors = ["Johnz86"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pyo3]
version = "0.13.2"
features = ["auto-initialize"]
```
main.rs
```Rust
use pyo3::prelude::*;
use pyo3::types::IntoPyDict;

fn main() -> Result<(), ()> {
    Python::with_gil(|py| {
        main_(py).map_err(|e| {
          // We can't display Python exceptions via std::fmt::Display,
          // so print the error here manually.
          e.print_and_set_sys_last_vars(py);
        })
    })
}

fn main_(py: Python) -> PyResult<()> {
    let sys = py.import("sys")?;
    let version: String = sys.get("version")?.extract()?;
    let locals = [("os", py.import("os")?)].into_py_dict(py);
    let code = "os.getenv('USER') or os.getenv('USERNAME') or 'Unknown'";
    let user: String = py.eval(code, None, Some(&locals))?.extract()?;
    println!("Hello {}, I'm Python {}", user, version);
    Ok(())
}
```
Try to run the project and fail
```
PS C:\GIT\Rust\call-python> cargo run
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.72
   Compiling proc-macro-hack v0.5.19
   Compiling winapi v0.3.9
   Compiling cfg-if v1.0.0
   Compiling inventory v0.1.10
   Compiling smallvec v1.6.1
   Compiling scopeguard v1.1.0
   Compiling unindent v0.1.7
   Compiling libc v0.2.94
   Compiling pyo3 v0.13.2
   Compiling instant v0.1.9
   Compiling lock_api v0.4.4
error: failed to run custom build command for `pyo3 v0.13.2`

Caused by:
  process didn't exit successfully: `C:\GIT\Rust\call-python\target\debug\build\pyo3-541bbc8efb2ac98e\build-script-build` (exit code: 1)
  --- stderr
  Error: "Python 3.x interpreter not found"
warning: build failed, waiting for other jobs to finish...
error: build failed
```
I tried to set PYO3_PYTHON
```
PYO3_PYTHON = C:\Python38
```
And I get: 
```
   Compiling pyo3 v0.13.2
error: failed to run custom build command for `pyo3 v0.13.2`

Caused by:
  process didn't exit successfully: `C:\GIT\Rust\call-python\target\debug\build\pyo3-541bbc8efb2ac98e\build-script-build` (exit code: 1)
  --- stderr
  Error: "Failed to run the Python interpreter at C:\\Python38: Access is denied. (os error 5)"
```

**Comment by marc2332** [comment]
Hello! I had the same issue.

 PYO3_PYTHON should point to the binary's exact path, not to it's parent folder.

Wrong:
`PYO3_PYTHON = C:\Python38`

Should work:
`PYO3_PYTHON = C:\Python38\python.exe`

👍🏻

**Comment by davidhewitt** [comment]
In addition, regarding the original usage of `Set-Alias` @Johnz86 posted, I'm afraid that we wouldn't be able to detect usage of `Set-Alias` - you'll need to either use `PYO3_PYTHON` as per answer above, or make sure that `python.exe` is somewhere on your `PATH`.

Sorry it took me so long to answer this.

**Comment by CrypptoPaul** [comment]
Hey there,
Would be extremely grateful if someone could detail how to do this:

PYO3_PYTHON = C:\Python38\python.exe  on windows.. dunno where to assign this variable I tried almost everywhere and nothing works.

**Comment by CrypptoPaul** [comment]
![image](https://user-images.githubusercontent.com/84225765/152071559-ba633569-9ad3-48e0-b80f-82ef4fa4e1c9.png)

**Comment by CrypptoPaul** [comment]
![image](https://user-images.githubusercontent.com/84225765/152071643-4a0cdee0-17e0-4e3b-8580-dd5bbc97b380.png)
I got the same error and its nuts, its actually working when importing and running the library, but when I try to fix the cargo.toml file I get this error, which is no sense, since the environment is there, as shown in the image after the error, its showing the python version, does anyone now how I configure it so its recognized by cargo.???

**Comment by jaraco** [comment]
I encountered this issue also.

Did you know on Windows, the default installation options don't include installing Python on the PATH, but the default installation options do include installing the `py` launcher on the PATH? Perhaps pyo3 could be smarter and fall back to `py -3` or simply `py` when no executable is specified.

I tried setting `PYO3_PYTHON=py` to see if a generic executable as found on the path could be supplied, so that I don't have to think about which Python executable to use, but that produced a different error:

```
Unable to create process using '"C:\Program Files\Python 3.11\py""': The system cannot find the file specified.
```

That error looks like it's revealing a couple of possible bugs:

- The mis-matched double-quotes suggest that maybe quotes are being added incorrectly.
- The routine seemingly inferred a Python installation at "C:\Program Files\Python 3.11", but then weirdly put $PYO3_PYTHON at the end of it, which isn't where the launcher is found. Why if the routine could find "C:\Program Files\Python 3.11" could it not find "python.exe" there?

Since the routine seemed to be able to infer the location of some Python executable, I tried setting `PYO3_PYTHON=python`, but that caused the Microsoft Store to launch, prompting install of Python 3.10, and pyo3 reported yet another error: `error: Python script failed`.

I guess the best thing for me to do is write my own logic to locate Python and to set PYO3_PYTHON to the location of that executable, but it would be nice if pyo3 could infer the location more consistently with what a user might expect on Windows, so that most users could rely on a default behavior, similar to how they can for launching Python interactively.

**Comment by davidhewitt** [comment]
We pass the value of `PYO3_PYTHON` directly into `std::process::Command`, and will subsequently use whatever executable is on your PATH.

The error "unable to create process" sounds like a bug somewhere else in the Python ecosystem. e.g. https://github.com/pypa/pip/issues/5223

It sounds like py.exe is on your path and is being picked up correctly, however somehow your installation may be corrupted? in general we haven't written support for the `py.exe` launcher, given a proposed design of how support for it should work I'd be happy to discuss on windows.
