### ISSUE TITLE
Performance idea: unlikely()/likely() annotations

### ISSUE THREAD

**Issue by itamarst** [PyO3/pyo3#1618]
Looking through PyO3 conversion code (Python → Rust) it's got a lot of branches where the error handling branch will likely never be taken in production code. Giving the compiler hints to that effect would allow moving the cold paths elsewhere, and therefore hopefully the processor instruction caches will be utilized better and allow for fewer reads from slower caches.

It's apparently possible to do `unlikely/likely` annotations on Rust stable using `#[cold]`: https://github.com/rust-lang/hashbrown/blob/master/src/raw/mod.rs#L51

**Comment by davidhewitt** [comment]
This is interesting, thanks for the suggestion. Using `#[cold]` internally could be worth experimenting with sometime. I'm not sure we're ready yet to apply loads of these kinds of optimizations as there's still a lot of higher-level rearchiteching we're doing.

**Comment by mejrs** [comment]
Let's give this a spin (setup below):

|using likely|successful prediction rate|avg time|
|--|--|--|
|yes|1 (all) |0.00396 |
|no|1  |0.00397 |
|no|0| 0.07460|
|yes| 0|0.07643|
|yes|99/100 |0.00488|
|yes|1/100 |0.07662|
|no|1/100 |0.07379|
|no|99/100 |0.00479|
|no|1/2|0.04111|
|yes|1/2|0.04112|

The general trend with `likely`, (which mirrors pure-Rust benchmarks in general) boils down to:
- if used correctly, i.e. the prediction is always correct, it doesn't do a whole lot because the compiler can usually figure out the happy path on its own
- If you rarely fail the prediction, it can be worse than **not** using `likely`
- usually the difference is lost in noise and it's hard to tell either way
- if you can't get a good real world benchmark showing a noticeable difference it's a bad idea to use it

> error handling branch will likely never be taken in production code.

Keep in mind also that Python programmers *do* like to use control flow through exceptions because they are relatively cheap (unlike Java for example). When used as such, using `unlikely` is probably not a good idea.

Also if you are interested in this I'd recommend you read the rust-lang github issues about it.

# Setup

This is not particularly scientific - if you can figure out a better setup, please do.

Cpu: `i5-3570 @ 3.40GHz` (I know, I suck)


Rust code:
```rust
#![feature(core_intrinsics)]

use pyo3::prelude::*;
use pyo3::types::PyList;

use std::collections::HashMap;
use std::intrinsics::likely;

#[pyfunction]
fn count_dicts(list: &PyList) -> u64 {
    list.iter().fold(0, |accumulator, item| {
        if likely(item.extract::<HashMap<usize,usize>>().is_ok()) {
            accumulator + 1
        } else {
            accumulator
        }
    })
}

#[pymodule]
fn my_module(py: Python, m: &PyModule) -> PyResult<()> {
    m.add_function(pyo3::wrap_pyfunction!(count_dicts, m)?)?;
    Ok(())
}
```

Python code:
```python
from my_module import count_dicts
from timeit import default_timer as timer
from random import randrange

d = dict()
l = list()

# change this to change prediction rate
my_list = [d if randrange(2) > 0 else l for _ in range(100000)]
#my_list = [d for _ in range(1000000)]

print("Started benchmark")

start = timer()

for n in range(100):
    count = count_dicts(my_list)


end = timer()

avg = (end - start)/100

print(f"Avg benchmark is {avg:.5f}")
```

**Comment by itamarst** [comment]
First, I am not sure that benchmark is representative of all cases. https://easyperf.net/blog/2019/11/22/data-driven-tuning-specialize-switch has an example where it does help. And if you look at the hashbrown link I gave, they talk about "consistently improving performance by 10-15%" for whatever internal usage they're doing.

Second, the specific cases I was thinking of is deserialization from Python objects to Rust objects, e.g. your Rust function expects `Vec<u64>`:

```rust
#[pyfunction]
fn sum(a: Vec<u64>) -> u64 {
    // ...
}
```

In this case there are many branches repeatedly checking "is this a Python int? does it fit in u64?" and in real-world code you'll almost never pass in data that doesn't fit that. And if you did you're in Python--exception-world, which is so expensive I bet it'll overwhelm any slowdown from hitting cold code paths.

It seems like the sort of place where telling the compiler "vast majority of the time this path will happen" is (a) true (b) likely to help performance.

**Comment by itamarst** [comment]
I guess, to add "how is that different from this benchmark"—

This benchmark has the `likely()` on the _outside_, so inside the hashmap extraction there's still a whole bunch of repeated branches without these hints. I am suggesting that the `likely()` inside the _inner_ branches is what will make a difference. E.g. https://github.com/PyO3/pyo3/blob/main/src/types/num.rs has a whole bunch of branches.

**Comment by davidhewitt** [comment]
Given we do make some use of `#[cold]` in the codebase now, and in general we continue to improve performance, I'm going to close this issue. Thanks for the suggestion!
