### ISSUE TITLE
Accepting a vector of custom #[pyclasses] with external types

### ISSUE THREAD

**Issue by curldivergence** [PyO3/pyo3#1739]
Hello. I have a question about exposing custom types to Python: let's say I have a type
```
#[pyclass]
struct Mesh {
    vertices: Vec<cgmath::Vector3<f32>>,
    indices: Vec<[u32; 3]>,
}
```
and am willing to expose a pyfunction that would accept a list of these structs:
```
#[pyfunction]
fn transform_objects(meshes: Vec<&Mesh>) -> PyResult<()>
```
But unfortunately, I'm getting an error that says that pyo3::FromPyObject is not implemented for Vec<&Mesh>.
On SO there is a related [question ](https://stackoverflow.com/questions/54213443/vector-of-custom-struct-in-pyo3) that explains why I need to accept a vector of *references*, but unfortunately, it doesn't help. 
As I understand (please correct me if I'm wrong) this happens because my type contains types from `cgmath` crate, and I'd need to derive that trait for cgmath::Vector3 (which I cannot due to the orphan rule). 
I can guess a typical workaround in such a case would be to introduce a newtype for Vector3, but then I'll loose all its nice methods :(
So could you give a bit of advice regarding what to do in such a case? :)

Thank you!

**Comment by birkenfeld** [comment]
You don't have to implement any PyO3 traits for the contents of the struct, as long as they're not exposed to Python (using `#[pyo3(get)]`, for example).

The StackOverflow answer is outdated; since then, PyO3 has become more strict with how Rust references to objects on the Python heap work, to avoid soundness issues.

What works now is `Vec<&PyCell<Mesh>>` or even easier, `Vec<PyRef<Mesh>>`. The `PyRef` here is analogous to a `Ref` that you get from borrowing a Rust `RefCell`.

That said, since PyO3 still *can* extract an `arg: &Mesh` argument (by auto-generating the `PyCell` borrowing code) I don't see why `Vec<&Mesh>` couldn't be made to work in principle. Maybe there's a trait resolution issue, @davidhewitt might know more.

**Comment by curldivergence** [comment]
Hi. `Vec<PyRef<Mesh>>` works indeed, thank you for your help :)

**Comment by davidhewitt** [comment]
> That said, since PyO3 still can extract an `arg: &Mesh` argument (by running the `PyCell` borrowing code during extraction) I don't see why `Vec<&Mesh>` couldn't be made to work in principle.

TBH the fact that we accept `&Mesh` is itself fairly magical. If the macro sees a reference as the argument type it switches from using the `FromPyObject` trait to using the `ExtractExt` trait. This lets us extract `PyRef<&Mesh>` behind the scenes in combination with a deref `&*` pair.

That trick wouldn't work with `Vec<&Mesh>` because instead we'd need to extract `Vec<PyRef<&Mesh>>` and then borrow it in a second `Vec<&Mesh>` rather than doing the deref.

So accepting `Vec<&Mesh>` is possible, but it'd force us to flesh out the `ExtractExt` trait further to abstract over the deref or the Vec conversion. I'm not sure I want to do that - this would most likely lead to all of the container types having to implement `ExtractExt`.

---

I was wondering about going the other direction and make it possible to make immutable-by-default classes _without_ `PyCell`. This would allow `&Mesh` to be extracted without any special code. `#[pyclass(pycell = true)]` would then enable `&mut` receivers and `PyRefMut<Mesh>` conversions elsewhere, at the cost of disabling regular `&Mesh` conversions.

I think this'd be nice because the base case without `PyCell` would be even faster performance-wise, and those who need mutability can have a well-documented opt-in to `PyCell` and how it affects the rest of their code. And we can remove the reference-based special case (`ExtractExt`) from the proc macro code.)

**Comment by birkenfeld** [comment]
Thanks, that makes a lot of sense.

Closing the issue, as the original problem has been addressed.
