### ISSUE TITLE
Using PyErr outside of the "with_gil" closure it was produced in

### ISSUE THREAD

**Issue by chris-laplante** [PyO3/pyo3#1815]
I am using the "auto-initialize" feature. 

The fact that PyErr is not bound by 'py seems to make it possible to write code like this:

```
use pyo3::{Python, PyErr};
use pyo3::exceptions::PyRuntimeError;
use pyo3::types::PyType;

fn main() {
    let mut err = None;
    Python::with_gil(|py| {
        // Do something that produces an error
        err = Some(PyErr::from_instance(PyType::new::<PyRuntimeError>(py)));
    });

    // ... sometime later, perhaps in a completely different part of the application

    Python::with_gil(|py| {
        // Consume the error
        if let Some(err) = err {
            assert_eq!(err.ptype(py), PyType::new::<PyRuntimeError>(py));
        }
    });
}
```

This compiles and runs fine. But is it OK to rely on? 

If it is OK, then is it because the same Python interpreter is being used in both closures (since "auto-initialize" feature is on)?

**Comment by birkenfeld** [comment]
`'py` does not represent the lifetime of an interpreter, but of holding the GIL.  All types using `Py<T>` and `PyObject` (which is akin to `Py<PyAny>`) are fine to hold across such periods, and `PyErr` is composed of those.

**Comment by chris-laplante** [comment]
Thanks for the quick reply!

**Comment by birkenfeld** [comment]
One more thing that wasn't obvious to me in the beginning: Methods of the object types I mentioned need a `py` argument to do anything useful (that involves the interpreter).  So while you can keep them on the Rust side, you can only operate on them while holding the GIL.  In contrast, `&PyAny` methods are fine without, since the existence of the reference is already "proof" enough.
