### ISSUE TITLE
Allow functions exposed to Python to have slices as parameters via the buffer protocol

### ISSUE THREAD

**Issue by Keithcat1** [PyO3/pyo3#2058]
A useful feature would be the ability for Rust functions to accept, say, a slice of u8, which then allows you to call it with a bytes object from Python and Rust will get a slice pointing to the byte objects memory. Calling this function with, say, an array of i64 would get a type error. This also conveniently supports read only buffers by simply not declaring the lice to be mutable.

**Comment by davidhewitt** [comment]
Does [`pyo3::PyBuffer<u8>`](https://docs.rs/pyo3/latest/pyo3/buffer/struct.PyBuffer.html) meet your needs? That should be possible to use as a `#[pyfunction]` argument already.

`&[u8]` already has a `FromPyObject` implementation which accepts Python `bytes` only.

In general it is not sound to hold Rust slices to mutable Python objects such as `bytearray`. See the docs for [`PyByteArray::as_bytes`](https://docs.rs/pyo3/latest/pyo3/types/struct.PyByteArray.html#method.as_bytes) for an explanation. So unfortunately we would not be able to extend `&[u8]` to support Python objects which may be mutable (like `bytearray`).

**Comment by Keithcat1** [comment]
I didn't know that #[pyfunction] acccepted &[u8] or PyBuffer<u8>. I seem to remember looking at PyBuffer's impl traits and not seeing FromPyObject or anything like that implemented.
However, isn't there a way to tell Python via the buffer protocol that a buffer is currently in use and shouldn't be resized?

**Comment by davidhewitt** [comment]
https://docs.rs/pyo3/latest/pyo3/buffer/struct.PyBuffer.html#impl-FromPyObject%3C%27source%3E

> However, isn't there a way to tell Python via the buffer protocol that a buffer is currently in use and shouldn't be resized?

It's down to the object which provides the buffer to not allow itself to be resized while the buffer is in use. The issue here is that mutable buffers can allow changing the bytes at any time, so it's incorrect to allow `&[u8]` slices to the buffer data.

This example shows undefined behaviour taking a `&[u8]` slice from a bytearray:

```
#[pyfunction]
fn UNSOUND_takes_buf_and_bytearray(buf: PyBuffer<u8>, bytearray: &PyByteArray) -> PyResult<()> {
    let py = bytearray.py();
    let bytes: &[u8] = unsafe { bytearray.as_bytes() };

    // Write to third byte
    buf.as_mut_slice(py).expect("buf must be writeable")[2].set(0);

    // Print byte sequence
    println!("{:?}", bytes);

    Ok(())
}
```

If `buf` and `bytearray` are the same object, then the safe write done to `buf` will change the contents of the `bytes` slice. This breaks the semantics of `&[u8]`, so this sequence of operations is not sound.

The error in this code is the `unsafe { bytearray.as_slice() }` - not all invariants of `&[u8]` are protected correctly by the author of this code.

This explains why PyO3 cannot hand out `&[u8]` slices in `#[pyfunction]` for arbitrary buffer-supporting objects such as `bytearray`.
