### ISSUE TITLE
Support Python 3.7 timezone in datetime bindings

### ISSUE THREAD

**Issue by pganssle** [PyO3/pyo3#207]
As part of #200 (which added the Python datetime bindings), the update for the full Python 3.7 interface, which includes:

- [`PyDateTime_TimeZone_UTC`](https://docs.python.org/3/c-api/datetime.html#c.PyDateTime_TimeZone_UTC)
- [`PyTimeZone_FromOffset`](https://docs.python.org/3/c-api/datetime.html#c.PyTimeZone_FromOffset)
- [`PyTimeZone_FromOffsetAndName`](https://docs.python.org/3/c-api/datetime.html#c.PyTimeZone_FromOffsetAndName)

The timezone API was added to CPython in [PR 5032](https://github.com/python/cpython/pull/5032).

I believe this can be accompanied on the Rust side by a `PyFixedTimeZone` object or something. It's worth noting that no `_Check` methods accompany this, because you are really not intended to subclass these things.

**Comment by pickfire** [comment]
Can I get some pointers on how to provide a wrapper for `PyDateTime_TimeZone_UTC`?

I see that we can do `PyObject::from_borrowed_ptr(py, PyDateTimeAPI.TimeZone_UTC)` but should we do it the same way as `python::NotImplemented()`? I wonder how should we handle the singleton in this case?

Also, how can one do `<PyXXXUTC as PyTryFrom>::try_from(ob)` when implementing `FromPyObject` for `chrono::Utc`? I don't get how do we `PyTryFrom` a thing that does not have a thin wrapper, even if we have, I am still confused if we can use `pyobject_native_type!` for this?

**Comment by davidhewitt** [comment]
@pickfire I'm thinking about the correct design for this; please allow me a few days.

**Comment by pickfire** [comment]
Just discussing, I will only get to use `FromOffset` (which correlates to chrono [`FixedOffset`](https://docs.rs/chrono/0.4.19/chrono/offset/struct.FixedOffset.html)) and `UTC` (which correlates to chrono [`UTC`](https://docs.rs/chrono/0.4.19/chrono/offset/struct.Utc.html)), so minimally I require those two, but while doing that I can probably add the `FixedOffsetWithName` as well.

I believe I can just start with `PyTimeZone_FromOffset` since that is straightforward. Maybe I will keep `UTC` for later.

**Comment by davidhewitt** [comment]
@pickfire maybe #1573 gets you started? With that PR you could do `ffi::PyDateTime_TimeZone_UTC.as_ref(py)` to get a `&PyAny` representing the singleton.
