### ISSUE TITLE
How can I fetch back a Rust struct from a PyObject, which is from Rust

### ISSUE THREAD

**Issue by astrojhgu** [PyO3/pyo3#227]
Suppose I return a Rust struct from Rust side to Python, which is then casted to PyObject.

Then I have another Rust function with ```#[pyfunction]``` attribute that wants to accept the previous PyObect (which is wrapping my Rust struct) as a parameter. I want to operate the actual Rust struct inside this Rust function. What should I do?

It seems not very clear how to implement a FromPyObject. Of course I can access the attributes with the method ```getattr``` of PyObject, but I think there should be a more direct way.

Thanks

**Comment by daiheitan** [comment]
I believe that a struct with `#[pyclass]` will implement `PyTypeInfo`. As `PyTryFrom` is auto-implemented for `PyTypeInfo`, you could (ideally) call `<MyClass as PyTryFrom>::try_from(py_obj_ref)`.

However, currently this throws a downcast error. I think maybe getattr is the only working approach

**Comment by kngwyu** [comment]
I think just to use `#[pyclass]` works.

**Comment by konstin** [comment]
As @kngwyu said

**Comment by zimond** [comment]
@konstin I think currently this does not work. Because `#[pyclass]` conversion relies on `PyTryFrom`, which contains a `is_instance` type check. However, currently it seems that `#[pyclass]` is not setting correct type information on types. So this type check always fails.

Also I did a quick search and found no tests related to this. Maybe I'm wrong or missing some obvious thing? Help wanted and thanks for your time.

**Comment by konstin** [comment]
@zimond If you have an example of code that should work but doesn't, please open a new issue a minimized exampled.
