### ISSUE TITLE
python can not get the environment which is set by rust

### ISSUE THREAD

**Issue by chatwyn** [PyO3/pyo3#2416]
Hi

When I Use Rust to Call Python， I use `std::env::set_var(k, y)` to set the environment in rust.  

Then I  use pyo3 to call Python Code, but I can not get the environment that just set in rust.

**Comment by davidhewitt** [comment]
Unfortunately, this is documented behaviour of the Python interpreter: https://docs.python.org/3/library/os.html#os.environ

> This mapping is captured the first time the [os](https://docs.python.org/3/library/os.html#module-os) module is imported, typically during Python startup as part of processing site.py. Changes to the environment made after this time are not reflected in [os.environ](https://docs.python.org/3/library/os.html#os.environ), except for changes made by modifying [os.environ](https://docs.python.org/3/library/os.html#os.environ) directly.

If you call `set_var` _before_ the Python interpreter is initialized, the environment variable will be picked up by Python. Otherwise, it's too late and the change to the environment won't be picked up.
