### ISSUE TITLE
could not compile `pyo3` 90 or so specialization errors.

### ISSUE THREAD

**Issue by cbartondock** [PyO3/pyo3#2647]
I am trying to install a python module on an M1 macbook, and pip is failing to do so. I have tracked the problem as far as pyo3, which fails to compile because of errors like:

```error[E0520]: "drop_impl" specializes an item from a parent "impl", but that item is not marked "default"
         --> /Users/cdock01/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.6.0/src/instance.rs:564:5
          |
      549 | impl<T: ToPyObject + ?Sized> ManagedPyRefDispatch for T {}
          | ------------------------------------------------------- parent "impl" is here
      ...
      564 |     fn drop_impl(_: &mut ManagedPyRef<T>) {}
          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot specialize default item "drop_impl"
          |
```
And then finally ```error: could not compile "pyo3" due to 89 previous errors```

That appear when running `pip install autopy`.
Output of `rustup show` is:

```
Default host: aarch64-apple-darwin
rustup home:  /Users/cdock01/.rustup

nightly-aarch64-apple-darwin (directory override for '/Users/cdock01')
rustc 1.66.0-nightly (ce7f0f1aa 2022-09-28)
```

**Comment by adamreichold** [comment]
PyO3 0.6 is really old (0.17 is current). Could you try this using a newer version of PyO3? Or at least a stable version of Rust?

(This might be really old code that uses nightly feature from that time. Those features do have the same stability guarantees as the rest of the Rust language and hence might have been broken by changes to the Rust compiler in the time since PyO3 0.6 was released.)

**Comment by cbartondock** [comment]
Oh good call, solution is here: https://pypi.org/project/autopy/

Somehow I missed it:

"Note: AutoPy currently requires the 2019-10-05 Rust nightly in order to build from source. This is to maintain compatibility with an older version of PyO3, as the latest version has dropped Python 2 support. Python 2 support will likely be dropped from AutoPy as well sometime later this year, depending on how necessary it is to upgrade to a more recent version of PyO3 or Rust. In the meantime, it may be necessary to install the required nightly via the following when building locally:

rustup install nightly 2019-10-05 --force
This is due to rustup complaining that it doesn't include certain components such as rustfmt."

**Comment by cbartondock** [comment]
Except that toolchain name is invalid. Looks like I need to find a replacement for autopy.

**Comment by adamreichold** [comment]
> Except that toolchain name is invalid. Looks like I need to find a replacement for autopy.

Yeah, they do not archive all those nightly that far back. I am not sure if this work, but dirty hack might be to install a stable version that was released around the same time (those should be archived much longer) and set the environment variable `RUSTC_BOOTSTRAP=1` to make its nightly features available?

But yes, updating `autopy` to use a recent version of PyO3 would certainly be best (especially since PyO3 does not require nightly any more).

**Comment by cbartondock** [comment]
In the end for me it's not worth using libraries that use ancient versions of their dependencies lol, I switched to [pynput](https://pynput.readthedocs.io/en/latest/mouse.html) and that worked fine.

**Comment by birkenfeld** [comment]
Yeah, the "later this year" would have been 2020.
