### ISSUE TITLE
RFC: support PyUnstable_*

### ISSUE THREAD

**Issue by mejrs** [PyO3/pyo3#3495]
Do we want to expose and use these? See https://docs.python.org/3/whatsnew/3.12.html#id4 and https://docs.python.org/3.12/c-api/stable.html#unstable-c-api

For example we can have a fast path for integer conversions using `PyUnstable_Long_IsCompact` and `PyUnstable_Long_CompactValue`

**Comment by davidhewitt** [comment]
I get the impression these are just a more formal naming given to what we commonly use in the `cpython` headers / non-abi3 builds. So if there's measurable benefit from using them I think it's fine to do so.

The only fear would be that because the cpython developers have given themselves mandate to change them between Python versions then these APIs might prove to be more volatile. I think only time will tell.

**Comment by davidhewitt** [comment]
I think the conclusion is that yes, we can use these APIs, just we'll have to make sure they're tested properly on each version. Will close this issue.
