### ISSUE TITLE
How will PyO3 work with the upcoming no-GIL Python?

### ISSUE THREAD

**Issue by bplevin36** [PyO3/pyo3#3576]
[PEP 703](https://peps.python.org/pep-0703/) is coming, so GIL-less CPython builds are going to be commonplace pretty soon.  What are the PyO3 maintainers' thoughts on how to support this?  I'm assuming it will require some PyO3 API changes/additions, since the soundness guarantees given by CPython itself will change dramatically (e.g. [Python critical sections](https://peps.python.org/pep-0703/#python-critical-sections) ).

I'm keenly interested in this, since all the extensions I've built with PyO3 have been for Flask servers, where getting GIL-usage right has been very important.  Just curious to see what direction you have in mind!

**Comment by messense** [comment]
You can follow the discussion in #2885.

**Comment by davidhewitt** [comment]
To just comment here to add my own thoughts - we've discussed extensively in #2885 some of the likely changes that need to happen to bring nogil support. I'm very excited about PyO3 supporting nogil, and this is something I want to work on in the very near future. Before that, I am personally working on changes to make #3382 happen because I think that needs to happen for many reasons. If others want to make a start on nogil support before then, I will gladly join in reviews.

**Comment by bplevin36** [comment]
Ah this is exactly what I was looking for.  I didn't think to search "nogil" as one word so I didn't see an existing issue about it.
