### ISSUE TITLE
Breaking change 0.6.0-alpha4 to 0.6.0

### ISSUE THREAD

**Issue by tafia** [PyO3/pyo3#430]
I guess this is not that important but I got a compile error after a cargo update.
- `PyObjectRef` has apparently disappeared.
- `FromPyObject` has changed.

The fix was simple enough.

**Comment by kngwyu** [comment]
`PyObjectRef` is renamed with `PyAny`.
So... should we have a document about it?

**Comment by tafia** [comment]
Yes I figured that out.
This is a breaking change (a `cargo update` shouldn't break your code). 
Also all the guides and the readme still mention 0.6-alpha4.
But apart from that I'm VERY pleased with pyo3 thanks!

**Comment by kngwyu** [comment]
Ah, OK, I'll fix them.
Thanks for reporting.

**Comment by tafia** [comment]
Technically I still think you should publish a v0.7 and yank version 0.6.

**Comment by kngwyu** [comment]
Hmm I read [semver spec](https://semver.org/#spec-item-9) and it looks OK to add a breaking change to pre-release version :thinking: 
BTW, I'll fix documents and thanks for reporting :+1:

**Comment by konstin** [comment]
The stability guarantees only apply to stable releases, not to pre-releases. There's some discussion in https://github.com/rust-lang/cargo/issues/2222 about how `cargo update` should deal with pre-releases. In general if you want to work with a prerelease (or a git version), you should pin the version with a `=`.

Because I've already looked it up, the [semver spec](https://semver.org/#spec-item-9) on that matter:

> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

>  Also all the guides and the readme still mention 0.6-alpha4.

I think that's the actual problem. Fixed in #431 and 781741ef2791180fa50deb65bb7b1b018d650b69

**Comment by tafia** [comment]
Ok got it. Thanks!
