### ISSUE TITLE
send PyErr through channel will cause dead lock

### ISSUE THREAD

**Issue by Liyixin95** [PyO3/pyo3#4498]
### Bug Description

As the title says.

### Steps to Reproduce

here is the reproduce code:
```
use pyo3::{exceptions::PyValueError, prelude::*};
use tokio::sync::{
    mpsc::{self, UnboundedReceiver},
    oneshot,
};

#[tokio::main]
async fn main() {
    let (tx, rx) = oneshot::channel();

    let (t, r) = mpsc::unbounded_channel();

    std::thread::spawn(|| {
        execute_loop(r);
    });

    t.send(tx).unwrap();

    let ret = rx.await.unwrap();

    println!("{ret:?}");
}

fn execute_loop(mut rx: UnboundedReceiver<oneshot::Sender<PyResult<()>>>) {
    Python::with_gil(|py| loop {
        while let Some(tx) = rx.blocking_recv() {
            let err = PyValueError::new_err("foo");
            let send = tx.send(Err(err));
            println!("after send: {send:?}");
        }
    })
}
```

The `after send` can be printed, but the `rx` will be blocked forever.

I hava tried some other situation, which the main thread can ended successfully:
1. send Ok instead of Err
2. remove the `Python::with_gil`
3. use `Result<(), String>` instead of `PyResult<()>`

### Your operating system and version

Debian GNU/Linux 11 (bullseye)

### Your Python version (`python --version`)

Python 3.9.2

### Your Rust version (`rustc --version`)

rustc 1.80.1 (3f5fd8dd4 2024-08-06)

### Your PyO3 version

0.22.2

### How did you install python? Did you use a virtualenv?

apt-get install python3

**Comment by birkenfeld** [comment]
Thanks for the report!

Perhaps not surprisingly, sending the `PyErr` through the channel actually works fine. The deadlock happens when trying to print out `ret` containing the error, because that needs to acquire the GIL to print the exception type, value and traceback objects.

The problem is that in your `execute_loop` function, you acquire the GIL and then never release it, since the `while` loop is running indefinitely. So the main thread never gets a chance to acquire the GIL for printing.

Try this instead:

```
fn execute_loop(mut rx: UnboundedReceiver<oneshot::Sender<PyResult<()>>>) {
    while let Some(tx) = rx.blocking_recv() {
        Python::with_gil(|py| {
            let err = Err(PyValueError::new_err_arg("foo"));
            dbg!(&err);
            // let err = Ok(());
            let send = tx.send(err);
            println!("after send: {send:?}");
        });
    }
}
```

(The outer `loop {}` is probably not doing anything useful, since after you get `None` once from `blocking_recv` you can't ever receive more.)

**Comment by birkenfeld** [comment]
Also, as you noted in your simplified example you don't need the `with_gil` wrapper, but probably you do when doing nontrivial work within the loop.
