### ISSUE TITLE
Make `GILOnceCell<Py<PyType>>`'s `get_or_try_init_type_ref` public

### ISSUE THREAD

**Issue by glevco** [PyO3/pyo3#4516]
Hi! 

Is there any reason why `GILOnceCell<Py<PyType>>`'s [`get_or_try_init_type_ref()`](https://github.com/PyO3/pyo3/blob/9eab2600cd31bce1f017c294d2c20deee7289e76/src/sync.rs#L204) is not public API? It's a useful function and it looks like it should be the default way of importing Python modules. I would be happy to open a PR changing it and updating the docs accordingly, if it makes sense.

Thanks in advance!

**Comment by davidhewitt** [comment]
Hey, thanks for the request. There's a couple of different factors at play here: 
- eventually, we should probably use "module state" for extension modules to store things like imports. This is still a way off but I think the way the CPython team wants us to do things instead of using `GILOnceCell`.
- There is also some debate about the immediate future for `GILOnceCell`. The python 3.13 freethreaded build removes the ability to synchronize using the GIL, so we are exploring solutions like #4512 and #4513

So overall, it's not the best time to be expanding the `GILOnceCell` API until we are more sure of its future direction.

**Comment by davidhewitt** [comment]
That said, we just merged #4511 so maybe it's fine to make this public for the short term. PR would be accepted.

**Comment by glevco** [comment]
Ok, thanks! I'll work on it.

**Comment by glevco** [comment]
@davidhewitt Done in https://github.com/PyO3/pyo3/pull/4542, can you please review it?
