### ISSUE TITLE
Datetime test fails in my local machine

### ISSUE THREAD

**Issue by kngwyu** [PyO3/pyo3#587]
[This line](https://github.com/PyO3/pyo3/blob/master/examples/rustapi_module/tests/test_datetime.py#L57) fails in my local environment(Arch Linux 64bit).
```bash
Python 3.7.4 (default, Jul 16 2019, 07:12:58) 
[GCC 9.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime as pdt
>>> MAX_DATETIME_FROM_TIMESTAMP = pdt.datetime.fromtimestamp(253402300799)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: year 0 is out of range
```

IMHO, we really need such a strict test?

**Comment by pganssle** [comment]
@kngwyu The fact that it's failing makes me think we *do* need the strict test. The extremes of the input range are likely sources for edge cases, and it seems that we've found a real bug possibly having to do with integer overflow.

What time zone are you in? It's not clear if this is a bug in PyO3 or CPython.

**Comment by pganssle** [comment]
Though actually that appears to not be in a test function. We should probably move anything that uses a `pdt` method into a `test_` function and use `datetime` literals for those constants.

When did it start failing?

**Comment by kngwyu** [comment]
@pganssle 
> What time zone are you in? 

Asia/Tokyo

> When did it start failing?

Sorry, I don' t remember clearly... but maybe it did 1~2 months ago.

**Comment by pganssle** [comment]
@kngwyu Hm... Fails for me too when using `TZ=Asia/Tokyo` (though the tests aren't failing for some reason even when I use `setenv` in `tox.ini`).

The failure mode is very strange but that may be a bug in Python itself. In this case, I think that when "max datetime from timestamp" was added, the person adding it didn't realize that that's sensitive to the time zone you are in (since `fromtimestamp` translates a timestamp in UTC(ish) into local time). The solution is to specify maximum and minimum timestamps as `datetime.datetime` literals and then add tests that they can be "round tripped" using the Pyo3 datetime bindings.

**Comment by konstin** [comment]
I've seen these failures too for some time; Interestingly I get different failures when I switch my timezone (Europe/Berlin) to another (e.g. Europe/London).
