### ISSUE TITLE
Add fn as_bytes to PyByteArray

### ISSUE THREAD

**Issue by calixteman** [PyO3/pyo3#632]
I understand the rational for to_vec (https://github.com/PyO3/pyo3/issues/373#issuecomment-512332696) but in my use case it won't never happen (I just need to read data and nothing will modified them).
So it'd be nice to avoid a useless copy here.

**Comment by programmerjake** [comment]
maybe it would work to return `&Cell<[u8]>`, since the Python value is both shared and mutable

**Comment by programmerjake** [comment]
`&Cell<[u8]>` would work, as far as I can tell, since it is both shared and mutable, and doesn't implement `Send`/`Sync`, so wouldn't be able to be passed into `allow_threads`, preventing access while the GIL is unlocked.

However, if Python interpreters are allowed to move the backing buffer during a garbage collection (or similar), then returning any reference wouldn't be safe, unless the buffer was somehow pinned. Not sure if interpreters are allowed to do that.

**Comment by davidhewitt** [comment]
I think the bytearray can be resized at any point in python code just by using `+=`  operator, so returning a reference to data in the bytearray is definitely unsafe.

We can add `pub fn data() -> *mut u8` which returns a pointer to the start of the backing buffer. It would need to have documented that the backing buffer may be relocated during any Python code execution so it's up to the user to tread carefully.

This would allow @calixteman to do what he wants via the `unsafe` api `std::slice::from_raw_parts`.

**Comment by kngwyu** [comment]
>We can add pub fn data() -> *mut u8 which returns a pointer to the start of the backing buffer. 

:+1:  but I'm also for `unsafe fn as_bytes(&self) -> &[u8]`. It would be convenient.
