### ISSUE TITLE
`#[new]` should support arrays

### ISSUE THREAD

**Issue by c410-f3r** [PyO3/pyo3#775]
Maybe a missing implementation?

```rust
use pyo3::prelude::*;

#[pyclass]
struct Foo {
  array: [i32; 2]
}

#[pymethods]
impl Foo {
  #[new]
  //pub fn new(array: [i32; 2]) -> Self {
  pub fn new(array: &[i32; 2]) -> Self {
    //Self { array }
    Self { array: *array }
  }
}
```

**Comment by davidhewitt** [comment]
Like with everything about arrays in Rust, we could write a solution to support arrays up to an arbitrary length (normally 32).

To do this for all sizes would require const generics being available.

A PR for this to support arrays up to length 32 is very welcome.

**Comment by c410-f3r** [comment]
I will gladly provide a PR for arrays (up to 32) using declarative macros with some mentoring and

**Comment by davidhewitt** [comment]
That would be awesome, thanks! I'll find some time to write some quick mentoring notes either tomorrow or the day after.

**Comment by davidhewitt** [comment]
Mentoring notes, as promised:

Take a look at the implementation of `FromPyObject` for `Vec<T>`. This is probably a good starting point. It uses specialization to do an optimization for `Buffer` objects, but we don't need that here - arrays of only 32 elements will be short enough that an optimization is kinda irrelevant. So you only need to care about the `extract_sequence` function.

As for the macro, you could structure it something like this:

```
macro_rules impl_array! {
    ($n:literal) => {
        impl FromPyObject for [T; $n]
            where T: FromPyObject
        {
            ...
        }
    };
}

impl_array!(0);
...  // call for each N
impl_array!(32);
```

You might be able to also make a trick so that `impl_array!` calls itself recursively, but that's a bit of fun you can play with yourself if you want.

If you're willing, it would be awesome to also have `IntoPy<PyObject>` implemented for arrays in the same way.

@c410-f3r ping me if you have any further questions on this. The help is much appreciated.

**Comment by c410-f3r** [comment]
Thank you, @davidhewitt
