### ISSUE TITLE
maturin examples

### ISSUE THREAD

**Issue by kngwyu** [PyO3/pyo3#807]
Now our examples are built by [setuptools-rust](https://github.com/PyO3/setuptools-rust), but since currently [maturin](https://github.com/PyO3/maturin) is (maybe more) widely used, we should also provide maturin examples.

**Comment by davidhewitt** [comment]
As I'm working on the experimental maturin support for #1040 I'm going to convert the existing examples to maturin soon, probably this week.

I'll add a new minimalist example showing `setuptools-rust` configuration.

**Comment by konstin** [comment]
You should be able to just leave the setuptools part in since maturin simply ignores those files, so that the setuptools fans still get an example.

**Comment by davidhewitt** [comment]
Having started playing around with this, I found that it's nicer to make separate `maturin` and `setuptools-rust` examples because then it's easier for users to see what configuration is needed depending on the packaging tool they chose.

I ran into a bit of a speedbump with the `tox` testing of the `maturin` example. You've seen already the PRs I put into `tox` and `maturin` to resolve this, though I still have issues because the PEP 517 out-of-tree build fails because the pyo3 `path = "../../"` obviously doesn't get found when building in a temporary directory.

I'm trying to decide if I should hack in a wrapper around maturin as a PEP 517 "inline backend" to solve this issue, or whether to give up and just test the `setuptools-rust` bit using tox.

Hopefully I can find some time to have another go at finishing this off soon.
