### ISSUE TITLE
Accessing the module object in `pyfunction`s

### ISSUE THREAD

**Issue by birkenfeld** [PyO3/pyo3#828]
In the C API, module-level functions get passed their registered module object as the `self` parameter.  This is very nice to interact with other module level API.

Can we (optionally?) make the module reference available in `pyfunction`s too?

**Comment by davidhewitt** [comment]
I'm nominating this for `0.12`.

**Comment by sebpuetz** [comment]
I'm taking a dive into this, although I have **no** idea what I'm getting into. I'll let you know if I'm getting stuck or if I don't think I'm the right person for this.

**Comment by davidhewitt** [comment]
❤️ Many thanks! I see two options:

- You can probably do a similar thing as this function we use to detect `Python` arguments: https://github.com/PyO3/pyo3/blob/4a05f2782ce0d31df8a80f7eb04795a930d66004/pyo3-derive-backend/src/utils.rs#L11

  (I guess here you'll be detecting `&PyModule`.)

- Alternatively, maybe it's more predictable if this becomes an option to the pyfunction macro instead of trying to auto-detect:

  ```
  #[pyfunction(pass_module)] 
  fn with_module(module: &PyModule) { }

  // or
  #[pyfunction]
  #[pyo3(pass_module)] 
  fn with_module(module: &PyModule) { }
  ```
  
I think I slightly prefer the `#[pyfunction(pass_module)]` design. All opinions welcome.

**Comment by davidhewitt** [comment]
Note: you might also need to consider `#[pyfn]` for the same functionality. One day I hope we merge those two things!

**Comment by sebpuetz** [comment]
I had a first go at the implementation, and we need to make some changes to the ffi-calls for function creation.

Currently the `slf` parameter in `#[pyfunction]`s is always a null-pointer. This happens because the second parameter passed to `PyCFunction_NewEx` is always null:
~~~Rust
pyo3::ffi::PyCFunction_New(
                    Box::into_raw(Box::new(_def.as_method_def())),
                    ::std::ptr::null_mut(),
                ),

[...]
pub unsafe fn PyCFunction_New(ml: *mut PyMethodDef, slf: *mut PyObject) -> *mut PyObject {
    #[cfg_attr(PyPy, link_name = "PyPyCFunction_NewEx")]
    PyCFunction_NewEx(ml, slf, ptr::null_mut())
}
~~~

This is the signature of `PyCFunction_NewEx`:

~~~C

PyObject *
PyCFunction_NewEx(PyMethodDef *ml, PyObject *self, PyObject *module)
{
    return PyCMethod_New(ml, self, module, NULL);
}
~~~

So we're setting `self` explicitly to NULL for `pyfunction`/`pyfn`. In order to change this, we need to get a pointer to the module object into the `fn __pyo3_get_function_X`. Steps required to do this are:

1. add `pub fn add_function(&self, wrapper: &impl Fn(Python, &Self) -> PyObject) -> PyResult<()>` on `PyModule`
2. change code-generation for `get_function` to also pass the module (Might as well eliminate the Python param at this point)
    - new signature for wrapped fns: `    fn __pyo3_get_function_NAME(py: Python, m: &PyModule) -> pyo3::PyObject`
3. replace `std::ptr::null_mut()` with `m.as_ptr()`
4. extract module from `_slf` arg in wrap: `let _mod = _py.from_borrowed_ptr::<pyo3::types::PyModule>(_slf);`
5. call the `pyfunction` with the additional module parameter

-------

`PyFunction_NewEx` also has a `module` parameter that seems to generally be set to a string with the module name, it gets exposed as the `__module__` attribute on functions and is part of the `repr` of function objects.

The above steps also provide the facilities to set this attribute, all that's left at that point is to get the module name from the `self` pointer in the `get_function` wrapper:
~~~Rust
let name = unsafe { pyo3::ffi::PyModule_GetNameObject(m.as_ptr()) };
~~~
And passing the method_def, the module pointer and the name object to `PyCFunction_NewEx` instead of `PyCFunction_New`.

-------

I have only implemented this manually based on expanded code, I haven't touched the proc-macros yet. I hope to find some time to start writing a PR later today or tomorrow!

**Comment by sebpuetz** [comment]
It looks like a lot of tests rely on "free" functions, i.e. not associated with any `PyModule`. In that case we can't pass a `PyModule` to the `get_function` wrapper. I feel like such functions are *not* the norm and mostly show up in special circumstances like tests. I'm not sure how we'd even be able to call a function in Python that's never been added to a module.

So, what do you think about adding a `free` attribute on `pyfunction` to toggle the `PyModule` param?
