### ISSUE TITLE
Difference in object creation

### ISSUE THREAD

**Issue by pashinin** [PyO3/pyo3#86]
in rust-cpython:

```
PyDict::new  -> PyDict
PyTuple::new  -> PyTuple
```

in pyo3:

```
PyDict::new  -> &PyDict
PyTuple::new  -> Py<PyTuple>
```

Why such difference? And if I use `PyDict::new` in a function how do I return `PyDict`? `&PyDict` causes lifetime errors.

**Comment by fafhrd91** [comment]
In pyo3 you can not own python objects like PyDict, PyTuple or custom classes because of safety.
Python requires GIL to access any c-api, so it is natural to express GIL lifetime with rust lifetimes.
when you get reference `&PyDict` it lifetime is the same as GIL lifetime. so it is possible statically
guarantee proper usage of GIL.
rust-cpython on other hand does not enforce GIL lifetime with rust lifetimes, 
so you have to explicitly pass `Python<'p>` to every method call,
even for custom classes rust-cpython generates methods that accepts `Python<'p>`
this

in pyo3, if you need to store python object, you have two options, you can convert `&PyDict` into `PyObject` or convert it to `Py<PyDict>`. Both just pointers, but `Py<PyDict>` contains type information.  if you need to return it back to python, you can do `.into()` or just return reference,
pyo3 is able to convert both to `*mut PyObject`.

here are examples:
```rust
fn my_fun1(&PyString, &PyDict) -> PyResult<&PyDict> {
    PyDict::new(s.py())
}

fn my_fun2(s: &PyString, &PyDict) -> PyResult<Py<PyDict>> {
    let d = PyDict::new(s.py());
    Ok(d.into())
}

fn my_fun3(s: &PyString, &PyDict) -> PyResult<PyObject> {
    let d = PyDict::new(s.py());
    Ok(d.into())
}
```

because pyo3 does not require `Python<'p>` in method calls, it is possible to
use standard library traits like `std::convert::From` or `?`, etc.

does it make sense?

**Comment by pashinin** [comment]
Yes, thank you for answer.

**Comment by messense** [comment]
Marking this as future documentation improvements.
