### ISSUE TITLE
Creating Rust bindings for Python Libraries

### ISSUE THREAD

**Issue by JesterOrNot** [PyO3/pyo3#925]
I saw that this organization also has a repo with [rust bindings for numpy](https://github.com/PyO3/rust-numpy) Is there a standard way to generate bindings with PyO3, I'd be interested in porting some libraries like [sympy](https://github.com/sympy/sympy) to Rust. And if there is no standard way is this a feature that would be considered in the future? (Also great job on this project!!)

**Comment by programmerjake** [comment]
This is kinda off-topic for this bug report, but you might find the [`algebraics`](https://docs.rs/crate/algebraics/0.2.0) crate I wrote useful, since it does a lot of things that are generally considered the domain of symbolic mathematics software (like sympy), it also has Python bindings built using PyO3. It does need to be updated for the latest version of PyO3, which I haven't yet got around to doing.

**Comment by JesterOrNot** [comment]
I'm specifically looking at the [solver](https://docs.sympy.org/latest/tutorial/solvers.html) library how was the numpy crate ported?

**Comment by kngwyu** [comment]
numpy exposes C-API entrypoint. See https://docs.rs/numpy/0.8.0/numpy/npyffi/array/static.PY_ARRAY_API.html for more.
