### ISSUE TITLE
PyObject methods require self to have GIL lifetime

### ISSUE THREAD

**Issue by programmerjake** [PyO3/pyo3#950]
Many `PyObject` member functions require `&'py self` to have the same lifetime as `Python<'py>`, preventing useful things like:
```rust
fn f(obj: &PyObject) -> u32 {
    let py: Python = ...;
    obj.extract(py).unwrap()
}
```
or
```rust
static PY_FN: OnceCell<PyObject> = OnceCell::new();

fn run_py_fn(py: Python) {
    PY_FN.get().unwrap().call0(py).unwrap();
}
```

**Comment by programmerjake** [comment]
Turns out this may not actually be an issue due to lifetime variance and reborrowing. Leaving open for someone else to double check.

**Comment by davidhewitt** [comment]
I agree that this is not an issue. It's only `.extract()`, `.cast_as()` and `.as_ref` which take `&'p self` - and in all cases this is necessary because the `PyObject` owns the reference of the e.g. `&PyAny` which might be extracted.

 I ran a quick test and all your examples above compiled successfully, so I will close this issue.
